# Generated by Django 2.2.2 on 2019-07-01 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190701_1431'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
